---
- name: Deleting Bastion
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
     - gce/authentication
     - gce/defaults
     - notification/slack_authentication
  vars:
     - bastion_name: "bastion"
  tasks:
     - include: commons/setting_defaults.yaml
       tags:
          - always

     - name: Deleting instance{{ ':' }} {{ bastion_name }}
       gce:
         instance_names: "{{ bastion_name }}"
         zone: "{{ zone }}"
         state: "absent"
         project_id: "{{ gce_project_id }}"
         credentials_file: "{{ gce_credentials_file }}"
         service_account_email: "{{ gce_service_account_email }}"
       ignore_errors: True
