---
- name: Starting  any instance and writing into /etc/hosts
  hosts: localhost
  connection: local
  become: True
  vars_files:
     - gce/authentication
     - gce/defaults
  tasks:
    - include: commons/setting_defaults.yaml
      tags:
         - always

    - name: instance is not defined
      fail: msg="instance is not defined"
      when: instance is not defined
      tags:
         - always

    - name: "Starting instance named: {{ instance }}"
      gce:
        instance_names: "{{ instance }}"
        state: "started"
        zone: "{{ zone }}"
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"

    - name: "Fetching Info: {{ instance }}"
      gce:
        instance_names: "{{ instance }}"
        zone: "{{ zone }}"
        project_id: "{{ gce_project_id }}"
        credentials_file: "{{ gce_credentials_file }}"
        service_account_email: "{{ gce_service_account_email }}"
      register: instance_status

    - set_fact: public_ip={{ instance_status.instance_data[0].public_ip }}

    - name: "Writing into /etc/hosts: {{ public_ip }} {{ bastion_name }}"
      lineinfile: dest=/etc/hosts state=present regexp="{{ instance }}" line="{{ public_ip }} {{ instance }}"
      become: True
      ignore_errors: True    

    - debug: msg="ssh root@{{ public_ip }} or ssh root@{{ instance }}"
