---
- name: Performing operations just after an OpenShift's installation is done
  hosts: localhost
  connection: local
  gather_facts: False 
  vars:
     projects_should_be_infranode:
          - default
          - openshift-infra
          - openshift-ansible-service-broker
  tasks:
     - name: Modify configuration in Master, so all Pods will be create in host=apps
       lineinfile: dest=/etc/origin/master/master-config.yaml  state=present regexp="defaultNodeSelector" line='  defaultNodeSelector{{ ':' }} "host=apps"'

     - name: Adding Jenkins Provisioning into Master Configuration File
       lineinfile: path=/etc/origin/master/master-config.yaml insertbefore=BOF line={{ item }}
       with_items:
          - "  serviceName{{ ':' }} jenkins-jnlp"
          - "  templateName{{ ':' }} jenkins-ephemeral"
          - "  templateNamespace{{ ':' }} openshift"
          - "  autoProvisionEnabled{{ ':' }} true"
          - "jenkinsPipelineConfig{{ ':' }}"

     - name: Restart OpenShift's Master
       service: name={{ item }} state=restarted
       with_items:
          - atomic-openshift-master-api
          - atomic-openshift-master-controllers

     - name: Make sure some key projects are running on Infra Node
       command: oc patch namespace/{{ item }} --patch '{"metadata"{{ ':' }} {"name"{{ ':' }} "{{ item }}","annotations"{{ ':' }} {"openshift.io/node-selector"{{ ':' }} "host=infra"}}}'
       with_items: "{{ projects_should_be_infranode }}"

     - name: Recreate Pods, so it will be on Infra Node
       command: oc delete pods --all --namespace {{ item }}
       with_items: "{{ projects_should_be_infranode }}"

     - name: "Canceling any openshift-ansible-service-broker deployment"
       command: oc rollout cancel dc/{{ item }} --namespace openshift-ansible-service-broker
       with_items:
          - asb-etcd
          - asb
       ignore_errors: True
       tags:
          - asb

     - name: "openshift-ansible-service-broker: Make sure it's running"
       command: oc rollout latest dc/{{ item }} --namespace openshift-ansible-service-broker
       with_items: 
          - asb-etcd
          - asb
       tags: 
          - asb
