apiVersion: v1
kind: BuildConfig
metadata:
  name: application
spec:
  triggers:
    - type: GitHub
      github:
        secret: githubtasks
    - type: Generic
      generic:
        secret: generictasks
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node('maven') {
           stage ('Build') {
             git '<YOUR REPO>'
             sh "mvn clean install -s configuration/cicd-settings.xml -DskipTests=true"
           }
   
           stage('Deploy') {
             sh "oc start-build tasks-app --from-file target/openshift-tasks.war --follow --wait=true -n rollout-example"
           }
        }
    type: JenkinsPipeline
    type: Generic
status:
  lastVersion: 0
